version: '3'
services:
  dev-jenkins-teama:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "50000:50000"

  stage-jenkins-teama:
    build:
      context: ./STAGE
      dockerfile: Dockerfile
    ports:
     - "8081:8080"
     - "50001:50000"

  prod-jenkins-teama:
    build:
      context: ./PROD
      dockerfile: Dockerfile
    ports:
     - "8082:8080"
     - "50002:50000"

    
